# Generated by Django 5.0.4 on 2024-04-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=65)),
                ('birth_date', models.DateField()),
                ('country', models.CharField(max_length=65)),
                ('city', models.CharField(max_length=65)),
                ('address', models.CharField(max_length=65)),
                ('salary', models.FloatField()),
                ('avatar', models.ImageField(upload_to='employee/')),
                ('specialty', models.CharField(max_length=55)),
                ('descriptions', models.TextField()),
            ],
        ),
    ]
