# Generated by Django 5.0.6 on 2024-05-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_noutbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(choices=[('Uzbekiston', 'Uzbekiston'), ('Qozogiston', 'Qozogiston'), ('Tojikiston', 'Tojikiston')], default='Uzbekiston', max_length=10),
        ),
    ]
